### ISSUE TITLE
How can I fix error `data.0.meta.res.files.0.ctime` ?

### ISSUE THREAD

**Issue by Ives-Natsume** [tick97115115/gospeed_api#1]
Hi, I'm new in coding, and when the issule happened, I don;t know how to fix it.
I just used functions provided in your test.py, and `data.0.meta.res.files.0.ctime` occurred most of the times.

My code:
```
from test_index import *

test_client = TestClassGospeedClientInstance()

try:
    test_client.test_create_a_task_and_get_task_info()
except Exception as e:
    print(e)
```

And I get this:

```
PS D:\workpath\RSS-Downloader> & D:/code/anaconda/envs/NetDev/python.exe d:/workpath/RSS-Downloader/src/downloader.py
1 validation error for GetTaskList_Response
data.0.meta.res.files.0.ctime
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

I tried to find the answer from your source code and I think `ctime` may be the reason, but I still don't know what I should do. Much thanks if you could tell me what I should do :)
```
class ResolveRequest_Response_Res_File(BaseModel):
    name: str
    path: str
    size: int
    ctime: str # ISO8601 UTC
```

**Comment by UniversalProgressions** [comment]
Sorry for my late, are you going to run unittest on your computer?

**Comment by UniversalProgressions** [comment]
I think that's because the ctime property received a None value, but the property can't be None.

So that triggered a TypeError, I will try to inspect that.

**Comment by UniversalProgressions** [comment]
I've runned test again, but with no Exception triggered. 

I will modify this property as Nullable in version 2.0.5 as the resolution.

**Comment by UniversalProgressions** [comment]
I've modified 'ctime' property as Nullable, you can try it again to see if it's been fixed.

**Comment by Ives-Natsume** [comment]
Hi, thank you for all your work :)
This error no longer happened after I update the package, though there comes new ones :(
I'll try to fix new errors on my own first :D
